language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - DISTRO="ubuntu"
  - PINS="httpaf-async:. httpaf-lwt-unix:. httpaf:."
  - PACKAGE="httpaf"
  - TESTS=true
  - POST_INSTALL_HOOK="opam install --with-test httpaf-async httpaf-lwt-unix && opam exec -- make examples"
  matrix:
  - OCAML_VERSION="4.07"
  - |
    PRE_INSTALL_HOOK="sudo apt-get install -y libgmp-dev; opam install tls"
    OCAML_VERSION="4.06"
  - OCAML_VERSION="4.05"
